### ISSUE TITLE
如何编译Openwrt用的ipt2socks

### ISSUE THREAD

**Issue by kousyougi** [zfl9/ipt2socks#11]
我在Ubuntu下面照着README的静态链接 libuv 编译了ipt2socks。
在Ubuntu上测试可以跑。
但拿到openwrt 19.07.1 x86_x64 下面执行出现下面这个错误。

> root@OpenWrt:/usr/sbin# ./ipt2socks
/bin/ash: ./ipt2socks: not found

请问如何能在Ubuntu下面编译openwrt 19.07.1 x86_x64 用的版本。
谢谢

**Comment by zfl9** [comment]
1. 自己用 openwrt 提供的工具链编译。
2. 自己去 openwrt 上手动进行本地编译。

> 直接将 Ubuntu 上编译好的文件拿到 openwrt 上肯定是不行的，虽说  openwrt 是 linux 发行版，但是和通常大家熟知的centos/ubuntu/debian是存在很大差异的。

**Comment by kousyougi** [comment]
`1.在 ubuntu 上用 openwrt 提供的工具链进行交叉编译。`
`2.直接在 openwrt 主机上进行本地编译`
试了第二个方法，少了好多套件，然后得到那些套件的唯一路径是编译openwrt的版本。非常难，对我来说几乎不可行。

第一个方法：我搜寻openwrt toolchain教学
参考 https://blog.csdn.net/u012349679/article/details/78182027
这个网页写 1.先拿openwrt SDK制作toolchain
2.用作好的toolchain，`x86_64-openwrt-linux-gnu-gcc ipt2socks.c -o ipt2socks`
大致的流程是这样吗？

另外 https://github.com/pexcn/openwrt-ipt2socks 好像也是制作的方法，但把抓下来的东西丢进 /SDK/package/ 里面，还是无法编译成功。不太会用。

谢谢

**Comment by zfl9** [comment]
大致的流程是这样吗？知道如何交叉编译就行了。或者你去 https://github.com/pexcn/openwrt-ipt2socks 请教下编译方法。

**Comment by pexcn** [comment]
> 另外 https://github.com/pexcn/openwrt-ipt2socks 好像也是制作的方法，但把抓下来的东西丢进 /SDK/package/ 里面，还是无法编译成功。不太会用。

既然你用 x86_64 的版本，那么可以到这里获取编译好的 ipk: https://github.com/openwrt-dev/feeds/tree/x86-64/base

注：OpenWrt 19.07.x x86_64 的 SDK 似乎有些 bug, 编译某些应用执行起来会发生段错误，这里我用了 18.06.7 的 SDK 来编译，生成的 ipk 在 19.07.x 上也是能用的

**Comment by kousyougi** [comment]
感激
