### ISSUE TITLE
High CPU usage under few TCP/UDP connections

### ISSUE THREAD

**Issue by ulinuxp** [zfl9/ipt2socks#12]
Version: 5128beb7c172122ee1b0c983fb3493b0ba647df9 
libuv:1.32.0
Linux Kernel: 4.14

I was trying 5128beb7c172122ee1b0c983fb3493b0ba647df9 on an OpenWRT router. It still crashes sometimes. 

If it runs constantly for 20 minutes, the CPU usage will grow to 50%. After manually restart it, the CPU usage will resume to 4%. The memory usage wasn't significantly different, though.

@zfl9  Do you know what could be the reason?

**Comment by zfl9** [comment]
此版本问题太多，不是非常建议使用，已打算用libev重构，不幸的是没时间去行动。

**Comment by ulinuxp** [comment]
OK. 
FYI, there is one written with libev, but it doesn't support UDP.
https://github.com/tiernano/transocks_ev/blob/master/transocks_ev.c

**Comment by zfl9** [comment]
参考倒是不需要，我缺的只是时间。。
