### ISSUE TITLE
旧的3.4内核padavan没有补丁的情况下无法使用端口复用

### ISSUE THREAD

**Issue by vpswiki** [zfl9/ipt2socks#16]
win32 and linux< 3.9 do not support SO_REUSEPORT.
编绎报错：netutils.c:77: error: 'SO_REUSEPORT' undeclared (first use in this function)
如何关闭这个功能

**Comment by zfl9** [comment]
> 目前版本的ipt2socks有个设计上的bug（误用了libuv的api），目前正在使用更轻便的libev重写。

这个确实，我待会改一下master上的源码，加个判断，仅在启用了多线程的时候才设置端口重用。

**Comment by zfl9** [comment]
已提交。

**Comment by vpswiki** [comment]
感谢您的修改，现在已经用上了，但是很遗憾是，跑在k2p上面做trojan的前端，一会就崩了。
另外 今后的libev版本 是否还会支持3.9以下的内核？

**Comment by zfl9** [comment]
支持2.6以上的内核。

**Comment by zfl9** [comment]
libev版本在dev分支，正在开发中

**Comment by vpswiki** [comment]
感谢您的工作，祝好。
