### ISSUE TITLE
Use splice() for low-end routers

### ISSUE THREAD

**Issue by simon-on-gh** [zfl9/ipt2socks#22]
>    splice() moves data between two file descriptors without copying
>        between kernel address space and user address space.  It transfers up
>        to len bytes of data from the file descriptor fd_in to the file
>        descriptor fd_out, where one of the file descriptors must refer to a
>        pipe.

http://man7.org/linux/man-pages/man2/splice.2.html

Also see 

https://github.com/wongsyrone/transocks-wong/blob/6ee0f0a821a7a144af6bfdf683aed0b75ea82433/src/splicepump.c#L68

**Comment by simon-on-gh** [comment]
It seems that the reference only supports TCP, though.
 https://github.com/wongsyrone/transocks-wong/issues/5

**Comment by zfl9** [comment]
http://man7.org/linux/man-pages/man2/splice.2.html

看了下文档，两个fd中必须至少有一个是pipe管道，所以没有意义。

**Comment by simon-on-gh** [comment]
Pipe is nothing but a buffer in the kernel. And with SPLICE_F_MOVE flag it moves data from socket, instead of copying it, into that buffer.

https://blog.cloudflare.com/sockmap-tcp-splicing-of-the-future/

**Comment by zfl9** [comment]
看起来似乎有点意思，周末在研究下

**Comment by zfl9** [comment]
不过看cf的那个博客，感觉sockmap更加有趣哈。

**Comment by zfl9** [comment]
> Pipe is nothing but a buffer in the kernel. And with SPLICE_F_MOVE flag it moves data from socket, instead of copying it, into that buffer.
> 
> https://blog.cloudflare.com/sockmap-tcp-splicing-of-the-future/

仔细想想其实是这个道理，只不过我现在是通过用户空间的一个buffer做中转，而利用splice()的话，其实就是用一个pipe管道充当这个buffer而已。

**Comment by zfl9** [comment]
> 
       SPLICE_F_MOVE
              Attempt to move pages instead of copying.  This is only a hint
              to the kernel: pages may still be copied if the kernel cannot
              move the pages from the pipe, or if the pipe buffers don't
              refer to full pages.  The initial implementation of this flag
              was buggy: therefore starting in Linux 2.6.21 it is a no-op
              (but is still permitted in a splice() call); in the future, a
              correct implementation may be restored.

**Comment by simon-on-gh** [comment]
![numbers-2mib-2](https://user-images.githubusercontent.com/63436921/81556827-8c4a4100-93bd-11ea-9074-7aaa74a3d25d.png)

The blog tests it with 4.14 kernel and it seems that the performance of splice() is pretty close to sockmap

**Comment by zfl9** [comment]
已替换为 splice() 接口。感觉还可以（在 rpi3b 上测试）。欢迎继续测试，感谢你的好建议。

**Comment by simon-on-gh** [comment]
Works great with glibc. Great job!

But it may still need some patch when compiling with uclibc, since splice may be still too new for it.

https://github.com/ThingMesh/openwrt-luci/blob/ac597e471793ff37b7ebc759f6bd8ffa744995dd/libs/nixio/src/splice.c#L45

**Comment by zfl9** [comment]
有编译报错的可以请请教下 @simon-on-gh （报错应该是 splice() 啥的未定义吧）。有这问题的应该都是嵌入式设备的Linux发行版
