### ISSUE TITLE
程序太容易崩溃了(nofile设置太小导致的，非功能性bug)

### ISSUE THREAD

**Issue by maskedeken** [zfl9/ipt2socks#24]
例如出现Too many open files的错误，没必要直接panic退出

**Comment by zfl9** [comment]
..nofile limit 调大点不就行了。

**Comment by maskedeken** [comment]
> 
> 
> ..nofile limit 调大点不就行了。

意思是这种错误没必要直接崩溃退出，等连接变少了就可以恢复正常，现在是程序退出了，每次都有手工重启

**Comment by maskedeken** [comment]
出现这种错误只要打印错误日志方便排查就行，查错的人可以选择逐步调整nofile直至一个合适的值，每次都崩溃太不友好了

**Comment by zfl9** [comment]
也有道理，有时间改一下。

**Comment by maskedeken** [comment]
看了一下代码，无论是connect出错、send出错和recv出错，都会直接退出evloop，这样不够友好，因为网络出错是常有的事，错误处理可以考虑鲁棒一点

**Comment by zfl9** [comment]
你看错了吧，connect/send/recv 报错不会退出 evloop。。

**Comment by maskedeken** [comment]
都直接tcp_context_release了，里面直接ev_io_stop

**Comment by zfl9** [comment]
大哥，ev_io_stop/start 操作的是 watcher。别搞笑

**Comment by zfl9** [comment]
去看看 libev 文档吧

**Comment by maskedeken** [comment]
原来这样，是我看错了

**Comment by zfl9** [comment]
退出进程只有在 socket/pipe/run_as_user 以及一些关键的 setsockopt 时发生。要是随便一个网络错误就退出，那还玩个蛋蛋。。

**Comment by maskedeken** [comment]
怎么可以先屏蔽掉Too many open files的错误让它不退出？因为每次都要上路由器重启程序。我只要知道它nofile不够就行

**Comment by zfl9** [comment]
netutils.c里面下面两个函数里的exit()去掉试试。
new_socket()
new_pipefd()

**Comment by cattyhouse** [comment]
> 怎么可以先屏蔽掉Too many open files的错误让它不退出？因为每次都要上路由器重启程序。我只要知道它nofile不够就行

systemd service 启动, `Restart=Always`

**Comment by maskedeken** [comment]
> 
> 
> > 怎么可以先屏蔽掉Too many open files的错误让它不退出？因为每次都要上路由器重启程序。我只要知道它nofile不够就行
> 
> systemd service 启动, `Restart=Always`

路由器一般都不用systemd

**Comment by cattyhouse** [comment]
> > > 怎么可以先屏蔽掉Too many open files的错误让它不退出？因为每次都要上路由器重启程序。我只要知道它nofile不够就行
> > 
> > 
> > systemd service 启动, `Restart=Always`
> 
> 路由器一般都不用systemd


```bash
#!/bin/bash
while true ; do
    pidof ipt2socks > /dev/null
    if [[ $? -ne 0 ]] ; then
        service ipt2socks restart
    fi
    sleep 10
done
```

**Comment by zfl9** [comment]
讨论方向有点偏了。周末我把那几条“没必要”的exit()语句去掉就行了。

**Comment by zfl9** [comment]
见1.1.3版本。
