### ISSUE TITLE
compile errors in alpine linux v3.12

### ISSUE THREAD

**Issue by windrosecn** [zfl9/ipt2socks#25]
Here are the error messages while compling:

`gcc -w -O2 -c libev/ev.c -o ev.o`
`gcc -std=c99 -Wall -Wextra -O2 -pthread -c ipt2socks.c -o ipt2socks.o`
`ipt2socks.c:40:28: error: unknown type name '__off64_t'; did you mean 'off64_t'?`
`   40 |   ssize_t splice(int fdin, __off64_t *offin, int fdout, __off64_t *offout, size_t len, unsigned int flags) {`
`      |                            ^~~~~~~~~`
`      |                            off64_t`
`ipt2socks.c:40:57: error: unknown type name '__off64_t'; did you mean 'off64_t'?`
`   40 |   ssize_t splice(int fdin, __off64_t *offin, int fdout, __off64_t *offout, size_t len, unsigned int flags) {`
`      |                                                         ^~~~~~~~~`
`      |                                                         off64_t`
`ipt2socks.c: In function 'tcp_stream_payload_forward_cb':`
`ipt2socks.c:743:25: warning: implicit declaration of function 'splice' [-Wimplicit-function-declaration]`
`  743 |         ssize_t nrecv = splice(self_watcher->fd, NULL, self_pipefd[1], NULL, TCP_SPLICE_MAXLEN, SPLICE_F_MOVE | SPLICE_F_NONBLOCK);`
`      |                         ^~~~~~`
`make: *** [Makefile:28: ipt2socks.o] Error 1`

gcc version is gcc (Alpine 9.3.0), I've installed libev and libev-dev from alpine package repository.

**Comment by zfl9** [comment]
更新再试。

**Comment by windrosecn** [comment]
no errors, but still some warnings:
`gcc -w -O2 -c libev/ev.c -o ev.o`
`gcc -std=c99 -Wall -Wextra -O2 -pthread -c ipt2socks.c -o ipt2socks.o`
`ipt2socks.c: In function 'tcp_stream_payload_forward_cb':`
`ipt2socks.c:40:58: warning: implicit declaration of function 'syscall' [-Wimplicit-function-declaration]`
`   40 |   #define splice(fdin, offin, fdout, offout, len, flags) syscall(__NR_splice, fdin, offin, fdout, offout, len, flags)`
`      |                                                          ^~~~~~~`
`ipt2socks.c:741:25: note: in expansion of macro 'splice'`
`  741 |         ssize_t nrecv = splice(self_watcher->fd, NULL, self_pipefd[1], NULL, TCP_SPLICE_MAXLEN, SPLICE_F_MOVE | SPLICE_F_NONBLOCK);`
 `     |                         ^~~~~~`
`gcc -std=c99 -Wall -Wextra -O2 -pthread -c logutils.c -o logutils.o`
`logutils.c: In function 'my_strerror':`
`logutils.c:10:12: warning: implicit declaration of function 'strerror_r'; did you mean 'strerror'? [-Wimplicit-function-declaration]`
`   10 |     return strerror_r(errnum, g_errstr_buffer, ERRSTR_BUFLEN);`
`      |            ^~~~~~~~~~`
`      |            strerror`
`logutils.c:10:12: warning: returning 'int' from a function with return type 'const char *' makes pointer from integer without a cast [-Wint-conversion]`
`   10 |     return strerror_r(errnum, g_errstr_buffer, ERRSTR_BUFLEN);`
`      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`gcc -std=c99 -Wall -Wextra -O2 -pthread -c lrucache.c -o lrucache.o`
`gcc -std=c99 -Wall -Wextra -O2 -pthread -c netutils.c -o netutils.o`
`gcc -std=c99 -Wall -Wextra -O2 -pthread -c protocol.c -o protocol.o`
`gcc -std=c99 -Wall -Wextra -O2 -pthread -s -o ipt2socks ipt2socks.o logutils.o lrucache.o netutils.o protocol.o ev.o -lm`

**Comment by zfl9** [comment]
编辑 Makefile，将 c99 改为 gnu99 试下。

**Comment by zfl9** [comment]
edit makefile...
make clean && make all

**Comment by zfl9** [comment]
明天我有时间再看下这个警告如何消除（alpine真是奇怪）。。。

**Comment by windrosecn** [comment]
把Makefile里的c99改为gnu99之后，出现同样的警告信息。

**Comment by windrosecn** [comment]
运行时出现的错误提示：
2020-06-09 10:58:47 ERR: [tcp_stream_payload_forward_cb] recv from client stream: (null)

**Comment by zfl9** [comment]
..这只是网络错误。只是errmsg没有打印出来。

**Comment by zfl9** [comment]
更新再试，看下是否还有警告。

**Comment by windrosecn** [comment]
警告没有了，编译正常
