### ISSUE TITLE
支持配置文件

### ISSUE THREAD

**Issue by PinkD** [zfl9/ipt2socks#3]
虽然纯命令行也能用，但是如果支持配置文件就可以直接改配置文件而不用改service文件，更直观也更方便

**Comment by zfl9** [comment]
改配置文件和改service文件不是一个道理吗？？？

**Comment by PinkD** [comment]
重启服务时多了一个 `systemctl daemon-reload` ，而且对于ArchLinux这种打包时习惯于把service文件放到 `/usr/lib/systemd/system` 的修改之前还需要手动把文件复制到 `/etc/systemd/system` 下

**Comment by PinkD** [comment]
不过这个issue只是个建议，如果觉得没有必要，可以关闭issue

**Comment by zfl9** [comment]
有时间再看吧，我自己当然不用配置文件，只是看你们的需求罢了。
