### ISSUE TITLE
可以分别转发端口吗？

### ISSUE THREAD

**Issue by yiguihai** [zfl9/ipt2socks#30]
像我有两台vps可能香港的机器延迟好点但是带宽小，美国的机器带宽大但是延迟高。
可不可以像redsocks一样把udp和tcp的转发地址和端口分开？

**Comment by zfl9** [comment]
可以启动两个 ipt2socks 进程，一个仅启用 TCP，一个仅启用 UDP。就能分别指定上游ip和端口了。

**Comment by yiguihai** [comment]
方法虽然有点笨，聊胜于无
