### ISSUE TITLE
请求增加fake dns功能

### ISSUE THREAD

**Issue by forever8938** [zfl9/ipt2socks#31]
查询真实ip是透明代理要解决的一个重要问题，想必不违背kiss原则。这项工作完全可以在本地完成，只需内置一个简易的DNS服务器，对每个域名返回唯一的假IP，并维护假IP到域名的映射。而走代理查询需要另外准备通道如ss-tunnel，延迟较高。

常见FQ软件中，clash支持fake dns。v2ray支持tls域名探测，但经常有抓不到域名的情况，而且不支持其他类型的流量如udp。v2ray也有人提交了这项功能的[PR](https://github.com/v2ray/v2ray-core/pull/2237)，暂未被接受。

**Comment by zfl9** [comment]
有什么用处呢

**Comment by forever8938** [comment]
> 有什么用处呢

你好，这个是解决DNS污染的一种方法，流程如下：

1. 客户端向ipt2socks查询www.google.com
2. ipt2socks返回1.2.3.4
3. 客户端向1.2.3.4发出TCP连接
4. ipt2socks拿到该连接，查表知1.2.3.4对应的是www.google.com
4. ipt2socks向socks端口发起请求，目标地址为domain=www.google.com

ipt2socks要查询映射表，所以fake dns必须集成在ipt2socks中。这个功能默认是关闭的。DNS服务器的话，只要支持A记录就够了，也可以用开源项目。

**Comment by zfl9** [comment]
每个域名都要一个唯一对应的fake_ip，我认为这不现实，必定会与正常的ip地址冲突，不接收这个功能请求。没有太大意义。

**Comment by zfl9** [comment]
ipt2socks 只做最纯粹的 tproxy/redirect -> socks5 转发。不喜欢加其他东西

**Comment by forever8938** [comment]
您可以不接受，这没问题。我解释几个点：

1. 这个方法是[rfc3089](https://tools.ietf.org/rfc/rfc3089)中定义的，不是FQ工作者发明的。
2. 只有gfwlist的域名需要fake ip。
3. fake ip通常使用的是保留地址，网段也是可以配置的。

**Comment by kousyougi** [comment]
代理工具套上fakedns上网体验变得好很多，还顺便解决ios擅自查询type 65 (HTTPS BINDING)的问题。
现在有fakedns功能的代理工具只有v2ray(xray)跟naiveproxy，其他trojan, hysteria都没有整合fakedns的功能。
我目前是用hysteria开socks5，然后开v2ray只做ipt2socks的工作，只是因为能支援fakedns，但这样肥得不得了，很多内存少的旧机器上跑不了。
如果能新开一条ipt2socks with fakedns 就太感激了。
