### ISSUE TITLE
谁可以分享一下 ipt2socks  ipatables透明代理规则。

### ISSUE THREAD

**Issue by youwei5683** [zfl9/ipt2socks#33]
我去看了 ss-proxy 没找到透明代理的ipatables规则。。 谁可以分享一下  谢谢 小弟是 debian10

**Comment by zfl9** [comment]
ss-tproxy里面有规则，可能你没有仔细看吧

**Comment by zfl9** [comment]
或者想更简单的版本，可参考下这个 https://gist.github.com/zfl9/d52482118f38ce2c16195583dffc44d2

**Comment by zfl9** [comment]
> 或者想更简单的版本，可参考下这个 https://gist.github.com/zfl9/d52482118f38ce2c16195583dffc44d2

将ss-redir替换为ipt2socks + socks5_proxy，其它好像也没啥可改的了。

**Comment by youwei5683** [comment]
感谢大佬的回复。我在研究一下 谢谢
```script
ss-redir -s MyIP -p MyPort -m MyMethod -k MyPasswd -b 127.0.0.1 -l 60080 --no-delay -u -T -v </dev/null &>>/var/log/ss-redir.log
```
我只要修改这里为 ipt2socks 的相关参数就可以了对吗？

**Comment by zfl9** [comment]
脚本应该很容易理解吧，照着改就行了
