### ISSUE TITLE
How can I forward ipt2socks TPROXY port to a subnet?

### ISSUE THREAD

**Issue by phantomcraft** [zfl9/ipt2socks#35]
With redirect in TCP, is easy:

iptables -t nat -A PREROUTING -i subnet0 -p tcp --syn -j DNAT --to-destination 127.0.0.1:60080

But how can I do the same redirection with TPROXY? How can I do the same with UDP?

**Comment by zfl9** [comment]
You can refer to these examples: 
- https://gist.github.com/zfl9/d52482118f38ce2c16195583dffc44d2 (a simple pure tproxy example)
- https://github.com/zfl9/ss-tproxy (redirect/tproxy script)

**Comment by phantomcraft** [comment]
Thanks.
