### ISSUE TITLE
建议增加dns to socks5这里的功能

### ISSUE THREAD

**Issue by qiuzi** [zfl9/ipt2socks#36]
因为dns2socks 不支持reuseport ， 希望这个能支持多dns服务器解析

**Comment by kousyougi** [comment]
是指dns fake ip吗？最近用v2ray的新功能fake ip还蛮好用的

**Comment by qiuzi** [comment]
fake ip没用过 ipt2要引进吗？

**Comment by zfl9** [comment]
emmm...我不希望在ipt2socks的基础上增加dns2socks5功能，如果要做，那也是新开一个项目(如zfl9/dns2socks5)这样，我希望ipt2socks保持简单。
