### ISSUE TITLE
请各位大佬帮我看看为什么用ipt2socks转UDP出错，xray转就没问题

### ISSUE THREAD

**Issue by gitv2ray** [zfl9/ipt2socks#38]
我在用ip2socks转发udp的时候出现错误，不知道哪里出错，请各位大佬帮我看看，谢谢!

1.tproxy 机 192.168.1.2 debian9 x64
2.brook 机 192.168.1.5 win10 x64
3.udp 请求机  192.168.1.9 win7 x64

我是在3 机使用 nslookup www.google.com 8.8.8.8 发出udp 请求，当使用xray 转发的时候一次通过正常。
当使用ip2socks转发的时候出错，nslookup 会发出5次udp 请求。

以下几张图是相关配置和出错信息。

![xray-linux-config-a](https://user-images.githubusercontent.com/71534870/126868667-3ed881bc-10a9-4350-9267-f57182386300.png)
![linux-iptables-a](https://user-images.githubusercontent.com/71534870/126868674-69516e20-28a7-4e9b-8e4c-06c7813e8038.png)
![xray-brook-good-a](https://user-images.githubusercontent.com/71534870/126868713-416fcdc8-1a7b-4b3c-9b84-68f5bf1dbf16.PNG)
![ipt2-brook-bad-a](https://user-images.githubusercontent.com/71534870/126868716-2d8a2b27-c22d-4562-a005-353dbe38f326.PNG)
![ipt2-brook-bad-linux-a](https://user-images.githubusercontent.com/71534870/126868721-b478a945-57c5-4e62-8447-21c154f1bbf8.PNG)

**Comment by zfl9** [comment]
这应该与ipt2socks没有关系，建议去socks5上游代理那里提issue。

**Comment by zfl9** [comment]
因为我之前是测试过ipt2socks配合v2ray的socks5代理的。具体v2ray（xray又是什么，最近很少关注这些了，哈哈）的配置我也不是很了解，估计你这个大概率是配置问题。

**Comment by zfl9** [comment]
哦不对，我看你用的socks5上游是brook（巧了，这些我都不是很熟悉）。

**Comment by gitv2ray** [comment]
今天试了一下，报告一下。
1.用v2ray 当brook机监听ip是 0.0.0.0的时候 出错，用wireshark查看，只有tcp包，没有udp包到1.5。ip 为192.168.1.5的时候就可以通过。
2.用xray，都可以，不知道它处理了什么
3.brook不知道怎么设置为192.168.1.5监听，可能如果能设置成1.5就能通过。

请问大佬，那些tcp包是ipt2socks发的吗?

**Comment by zfl9** [comment]
ipt2socks <-> socks5_server  之间的所有通信都是tcp协议（无论是tcp代理还是udp代理）。
