### ISSUE TITLE
ERROR: package/feeds/helloworld/ipt2socks failed to build.

### ISSUE THREAD

**Issue by wuxjjj** [zfl9/ipt2socks#47]
编译过程出现错误
make[2] -C feeds/helloworld/chinadns-ng download
 make[2] -C feeds/helloworld/dns2tcp download
 make[2] -C feeds/helloworld/dns2socks download
 make[2] -C feeds/helloworld/hysteria download
 make[2] -C feeds/helloworld/ipt2socks download
 make[2] -C feeds/helloworld/lua-neturl download
 make[2] -C feeds/helloworld/microsocks download
 make[2] -C feeds/helloworld/luci-app-ssr-plus download
 make[2] -C feeds/helloworld/redsocks2 download
 make[2] -C feeds/helloworld/naiveproxy download
 make[2] -C feeds/helloworld/shadowsocksr-libev download
 make[2] -C feeds/helloworld/simple-obfs download
 make[2] -C feeds/helloworld/tcping download
 make[2] -C feeds/helloworld/trojan download
 make[2] -C feeds/helloworld/v2ray-plugin download
    ERROR: package/feeds/helloworld/ipt2socks failed to build.
 make[2] -C feeds/helloworld/xray-core download
make package/download: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
 make[1] target/download
 make[2] -C target/linux download

make[3]: Entering directory '/workdir/openwrt/feeds/helloworld/ipt2socks'
mkdir -p /workdir/openwrt/dl
SHELL= flock /workdir/openwrt/tmp/.ipt2socks-1.1.3.tar.gz.flock -c '  	/workdir/openwrt/scripts/download.pl "/workdir/openwrt/dl" "ipt2socks-1.1.3.tar.gz" "73a2498dc95934c225d358707e7f7d060b5ce81aa45260ada09cbd15207d27d1" "" "https://codeload.github.com/zfl9/ipt2socks/tar.gz/v1.1.3?"    '
+ curl -f --connect-timeout 20 --retry 5 --location https://codeload.github.com/zfl9/ipt2socks/tar.gz/v1.1.3?/ipt2socks-1.1.3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  109k  100  109k    0     0  2545k      0 --:--:-- --:--:-- --:--:-- 2545k
Hash of the downloaded file does not match (file: 5279eb1cb7555cf9292423cc9f672dc43e6e214b3411a6df26a6a1cfa59d88b7, requested: 73a2498dc95934c225d358707e7f7d060b5ce81aa45260ada09cbd15207d27d1) - deleting download.
+ curl -f --connect-timeout 20 --retry 5 --location https://sources.cdn.openwrt.org/ipt2socks-1.1.3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://sources.openwrt.org/ipt2socks-1.1.3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://mirror2.openwrt.org/sources/ipt2socks-1.1.3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
No more mirrors to try - giving up.
make[3]: *** [Makefile:46: /workdir/openwrt/dl/ipt2socks-1.1.3.tar.gz] Error 2
make[3]: Leaving directory '/workdir/openwrt/feeds/helloworld/ipt2socks'
time: package/feeds/helloworld/ipt2socks/compile#0.19#0.06#1.06
    ERROR: package/feeds/helloworld/ipt2socks failed to build.
make[2]: *** [package/Makefile:116: package/feeds/helloworld/ipt2socks/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_compile] Error 2
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

**Comment by zfl9** [comment]
改一下hash值应该就可以了，昨天我更新了一下v1.1.3版本的makefile。。

**Comment by wuxjjj** [comment]
OK，多谢
