### ISSUE TITLE
作者你好，可以连接加密的socks5代理服务器么

### ISSUE THREAD

**Issue by monlor** [zfl9/ipt2socks#5]
如题，有个用socks5来做穿透的需求，利用socks5连接家里的局域网

**Comment by zfl9** [comment]
socks5 的用户名密码“加密”（严格来说只是“认证”）其实是明文传输的。需要的话可以加个选项传递用户名和密码，现在的版本不支持，周末有时间在搞。

**Comment by zfl9** [comment]
见最新release版本。
