### ISSUE TITLE
当socks服务开在本地服务器时，则会陷入socks循环请求，无法正常使用

### ISSUE THREAD

**Issue by L-codes** [zfl9/ipt2socks#50]
172.16.1.4 是服务器的IP，在上面开了一个 socks5 172.16.1.4:1080

启动 ipt2socks 用作 REDIRECT 透明代理
```bash
ipt2socks -R -u ltproxy -s 172.16.1.4 -p 1080 -l 60633
```

为了简单，这里只对 113.31.103.132 进行透明代理
```bash
iptables -t nat -N LLTPROXY
iptables -t nat -A PREROUTING -p tcp -j LLTPROXY
iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner ltproxy -j LLTPROXY
iptables -t nat -A LLTPROXY -p tcp -d 113.31.103.132 -j REDIRECT --to-port 60633
```

上面的配置，会陷入socks循环请求，无法正常使用

当不是使用本地搭建的socks时，使用外部的 socks 又没有问题，请问怎么解决？

**Comment by zfl9** [comment]
ipt2socks 和 socks进程 都以相同的用户身份（ltproxy）运行试试？

**Comment by L-codes** [comment]
这个方法确实可以，可是我还想问问有其它的方案吗？

**Comment by zfl9** [comment]
如果这个方法可以，说明问题的根本原因是：iptables规则未放行socks5进程的传出流量。

- 在 OUTPUT 链，你对所有非 ltproxy 用户身份的进程都进行了 REDIRECT 操作
- 因为 socks 进程运行在本机（与 ipt2socks 同一个主机），所以 socks 进程传出的流量，也走 OUTPUT 链
- 如果没有将这部分流量“放行”，那么会被 REDIRECT to ipt2socks，然后来到 socks 进程，构成了一个死循环

除了我说的方法（利用 `-m owner ! --uid-owner ltproxy` 来放行），还可以：

- 如果 socks进程 支持给传出的流量打 mark（SO_MARK），可利用 `-m mark $MARK` 来“放行”
- 如果 socks进程 的传出流量的 dst ip 是固定的，也可以简单的使用 `! -d $DST_IP` 来“放行”
- 将 socks5进程 运行在一个给定的 cgroup 内，然后利用 cgroup 放行：`-m cgroup --path <PATH>`

> 具体什么方法，看你自己选择，哪个方便就用哪个。
