### ISSUE TITLE
ip6tables v1.8.10 (legacy): unknown option "--set-xmark"

### ISSUE THREAD

**Issue by basncy** [zfl9/ipt2socks#56]
Archlinux, 滚挂了, 内核移除了Extension MARK?

https://gist.github.com/zfl9/d52482118f38ce2c16195583dffc44d2#file-ssredir_tproxy-sh-L44   v6版本添加失败.
Warning: Extension MARK revision 0 not supported, missing kernel module?
ip6tables v1.8.10 (legacy): unknown option "--set-xmark"
Try `ip6tables -h' or 'ip6tables --help' for more information.

Archlinux可用的最高内核版本 6.6.56-1-lts   6.11.3
Bug出现版本6.6.57-1-lts  6.11.4

蹲个后续, 插个眼看看其它发行版会不会跟着掉坑.

**Comment by zfl9** [comment]
https://github.com/tailscale/tailscale/issues/13863

**Comment by basncy** [comment]
Archlinux works on 6.6.59-1-lts and 6.11.6-arch1-1
